export {
  logger,
  createLogger,
  createRequestLogger,
  logEvent,
  logError,
  audit,
  logPerformance,
  LogLevel,
  EventType,
} from './logger.js';

export {
  initSentry,
  captureException,
  captureMessage,
  setUser,
  clearUser,
  addBreadcrumb,
  setTag,
  setExtra,
  startTransaction,
  requestHandler as sentryRequestHandler,
  tracingHandler as sentryTracingHandler,
  errorHandler as sentryErrorHandler,
  flush as flushSentry,
  close as closeSentry,
  Sentry,
} from './sentry.js';

export {
  register,
  client,
  getMetrics,
  getMetricsJson,
  getContentType,
  clearMetrics,
  httpRequestsTotal,
  httpRequestDuration,
  httpRequestSize,
  httpResponseSize,
  httpActiveRequests,
  recordHttpRequest,
  wsConnectionsTotal,
  wsActiveConnections,
  wsMessagesTotal,
  wsMessageSize,
  wsLatency,
  recordWsMessage,
  gatewayRequestsTotal,
  gatewayRequestDuration,
  gatewayStatus,
  recordGatewayRequest,
  sessionsTotal,
  activeSessions,
  sessionDuration,
  searchRequestsTotal,
  searchDuration,
  searchResultsCount,
  recordSearch,
  fileOperationsTotal,
  fileOperationDuration,
  fileSize,
  recordFileOperation,
  errorsTotal,
  recordError,
  chatMessagesTotal,
  chatMessageDuration,
  memoryQueriesTotal,
  customGauge,
  customCounter,
  customHistogram,
  setCustomGauge,
  incCustomCounter,
  observeCustomHistogram,
  systemCpuUsage,
  systemMemoryUsage,
  systemLoadAverage,
  updateSystemMetrics,
} from './metrics.js';

export {
  startSpan,
  withSpan,
  withSpanSync,
  getCurrentSpan,
  addSpanAttribute,
  addSpanAttributes,
  addSpanEvent,
  setSpanError,
  setSpanOk,
  SpanAttributes,
  EventNames,
  traceGatewayCall,
  traceSearch,
  traceFileOperation,
  createSpanContext,
  injectTraceHeaders,
  trace,
  context,
  SpanStatusCode,
  SpanKind,
} from './spans.js';

export {
  requestIdMiddleware,
  requestLoggingMiddleware,
  metricsMiddleware,
  tracingMiddleware,
  sentryBreadcrumbMiddleware,
  errorTrackingMiddleware,
  observabilityMiddleware,
} from '../middleware/observability.js';

export {
  healthRouter,
  setReady,
  setShuttingDown,
  addHealthCheck,
  removeHealthCheck,
} from '../routes/health.js';
