/**
 * Completion command - Generate shell completions
 */

import { Command } from 'commander';
import chalk from 'chalk';
import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { homedir } from 'os';
import { success, error, info } from '../lib/output.js';

/**
 * Create the completion command
 */
export function completionCommand() {
  const cmd = new Command('completion')
    .description('Generate shell completion scripts');
  
  // Generate bash completion
  cmd
    .command('bash')
    .description('Generate bash completion script')
    .option('-o, --output <file>', 'Output file path')
    .option('--install', 'Install to ~/.local/share/bash-completion/completions/')
    .action((options) => generateCompletion('bash', options));
  
  // Generate zsh completion
  cmd
    .command('zsh')
    .description('Generate zsh completion script')
    .option('-o, --output <file>', 'Output file path')
    .option('--install', 'Install to ~/.zsh/completions/')
    .action((options) => generateCompletion('zsh', options));
  
  // Show setup instructions
  cmd
    .command('setup')
    .description('Show shell completion setup instructions')
    .action(showSetupInstructions);
  
  return cmd;
}

/**
 * Generate bash completion script
 */
function generateBashCompletion() {
  return `#!/bin/bash
# ALFIE CLI bash completion script
# Generated by alfie completion bash

_alfie_completions() {
    local cur prev opts commands
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    
    # Top-level commands
    commands="chat search session file export import config completion status consensus verify procedure"
    
    # Global options
    global_opts="-h --help -v --version -q --quiet --no-color -c --config"
    
    # Command-specific completions
    case "\${COMP_WORDS[1]}" in
        chat)
            opts="-m --model -t --temperature --no-context --max-tokens -s --system -o --output --history"
            ;;
        search)
            opts="-n --limit -t --threshold -c --collection -f --filter -o --output --stats"
            ;;
        session)
            local session_cmds="list show delete new resume"
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( \$(compgen -W "\${session_cmds}" -- \${cur}) )
                return 0
            fi
            case "\${COMP_WORDS[2]}" in
                list|ls)
                    opts="-n --limit --all -o --output"
                    ;;
                show)
                    opts="--messages -o --output"
                    ;;
                delete|rm)
                    opts="-f --force"
                    ;;
                new)
                    opts="-n --name -m --model"
                    ;;
                resume)
                    opts=""
                    ;;
            esac
            ;;
        file)
            local file_cmds="list read write search info"
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( \$(compgen -W "\${file_cmds}" -- \${cur}) )
                return 0
            fi
            ;;
        export)
            local export_cmds="sessions memories config workspace"
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( \$(compgen -W "\${export_cmds}" -- \${cur}) )
                return 0
            fi
            ;;
        import)
            local import_cmds="sessions config workspace"
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( \$(compgen -W "\${import_cmds}" -- \${cur}) )
                return 0
            fi
            ;;
        config)
            local config_cmds="get set reset list edit"
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( \$(compgen -W "\${config_cmds}" -- \${cur}) )
                return 0
            fi
            ;;
        completion)
            local completion_cmds="bash zsh setup"
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( \$(compgen -W "\${completion_cmds}" -- \${cur}) )
                return 0
            fi
            ;;
        consensus)
            opts="-t --type --temperature -o --output"
            ;;
        verify)
            opts="-c --category -s --sources -o --output"
            ;;
        procedure)
            local proc_cmds="list search create show stats"
            if [[ \${COMP_CWORD} -eq 2 ]]; then
                COMPREPLY=( \$(compgen -W "\${proc_cmds}" -- \${cur}) )
                return 0
            fi
            ;;
        status)
            opts="--json"
            ;;
        *)
            COMPREPLY=( \$(compgen -W "\${commands}" -- \${cur}) )
            return 0
            ;;
    esac
    
    if [[ \${cur} == -* ]]; then
        COMPREPLY=( \$(compgen -W "\${opts} \${global_opts}" -- \${cur}) )
    elif [[ -n "\${opts}" ]]; then
        COMPREPLY=( \$(compgen -W "\${opts}" -- \${cur}) )
    fi
}

complete -F _alfie_completions alfie
`;
}

/**
 * Generate zsh completion script
 */
function generateZshCompletion() {
  return `#compdef alfie
# ALFIE CLI zsh completion script
# Generated by alfie completion zsh

_alfie() {
    local -a commands
    commands=(
        'chat:Chat with ALFIE'
        'search:Search ALFIE\\'s second brain'
        'session:Manage chat sessions'
        'file:File operations'
        'export:Export ALFIE data'
        'import:Import ALFIE data'
        'config:Manage configuration'
        'completion:Generate shell completions'
        'status:Check ALFIE status'
        'consensus:Multi-model consensus query'
        'verify:Verify claims'
        'procedure:Manage procedures'
    )
    
    _arguments -C \\
        '-h[Show help]' \\
        '--help[Show help]' \\
        '-v[Show version]' \\
        '--version[Show version]' \\
        '-q[Quiet mode]' \\
        '--quiet[Quiet mode]' \\
        '--no-color[Disable colors]' \\
        '-c[Config file]:config file:_files' \\
        '--config[Config file]:config file:_files' \\
        '1:command:->command' \\
        '*::arg:->args'
    
    case "$state" in
        command)
            _describe -t commands 'alfie commands' commands
            ;;
        args)
            case \${words[1]} in
                chat)
                    _arguments \\
                        '-m[Model to use]:model:(local-120b local-20b anthropic/claude-3.5-sonnet openai/gpt-4-turbo)' \\
                        '--model[Model to use]:model:(local-120b local-20b anthropic/claude-3.5-sonnet openai/gpt-4-turbo)' \\
                        '-t[Temperature]:temperature:' \\
                        '--temperature[Temperature]:temperature:' \\
                        '--no-context[Disable context]' \\
                        '--max-tokens[Max tokens]:tokens:' \\
                        '-s[System prompt]:prompt:' \\
                        '--system[System prompt]:prompt:' \\
                        '-o[Output format]:format:(text json markdown)' \\
                        '--output[Output format]:format:(text json markdown)' \\
                        '*:message:'
                    ;;
                search)
                    _arguments \\
                        '-n[Limit results]:limit:' \\
                        '--limit[Limit results]:limit:' \\
                        '-t[Score threshold]:threshold:' \\
                        '--threshold[Score threshold]:threshold:' \\
                        '-c[Collection]:collection:' \\
                        '--collection[Collection]:collection:' \\
                        '-o[Output format]:format:(text json table)' \\
                        '--output[Output format]:format:(text json table)' \\
                        '--stats[Show stats]' \\
                        '*:query:'
                    ;;
                session)
                    local -a session_commands
                    session_commands=(
                        'list:List sessions'
                        'show:Show session details'
                        'delete:Delete a session'
                        'new:Create new session'
                        'resume:Resume a session'
                    )
                    _describe -t session_commands 'session commands' session_commands
                    ;;
                file)
                    local -a file_commands
                    file_commands=(
                        'list:List files'
                        'read:Read a file'
                        'write:Write to a file'
                        'search:Search files'
                        'info:Show file info'
                    )
                    _describe -t file_commands 'file commands' file_commands
                    ;;
                export)
                    local -a export_commands
                    export_commands=(
                        'sessions:Export sessions'
                        'memories:Export memories'
                        'config:Export config'
                        'workspace:Export workspace'
                    )
                    _describe -t export_commands 'export commands' export_commands
                    ;;
                import)
                    local -a import_commands
                    import_commands=(
                        'sessions:Import sessions'
                        'config:Import config'
                        'workspace:Import workspace'
                    )
                    _describe -t import_commands 'import commands' import_commands
                    ;;
                config)
                    local -a config_commands
                    config_commands=(
                        'get:Get config value'
                        'set:Set config value'
                        'reset:Reset to defaults'
                        'list:List all config'
                        'edit:Edit interactively'
                    )
                    _describe -t config_commands 'config commands' config_commands
                    ;;
                completion)
                    local -a completion_commands
                    completion_commands=(
                        'bash:Generate bash completion'
                        'zsh:Generate zsh completion'
                        'setup:Show setup instructions'
                    )
                    _describe -t completion_commands 'completion commands' completion_commands
                    ;;
            esac
            ;;
    esac
}

_alfie "$@"
`;
}

/**
 * Generate and optionally install completion
 */
async function generateCompletion(shell, options) {
  const script = shell === 'bash' ? generateBashCompletion() : generateZshCompletion();
  
  if (options.install) {
    let installPath;
    
    if (shell === 'bash') {
      installPath = join(homedir(), '.local', 'share', 'bash-completion', 'completions', 'nexus');
    } else {
      installPath = join(homedir(), '.zsh', 'completions', '_alfie');
    }
    
    const dir = dirname(installPath);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    
    writeFileSync(installPath, script);
    success(`Installed ${shell} completion to ${installPath}`);
    
    if (shell === 'bash') {
      info('Restart your shell or run: source ~/.bashrc');
    } else {
      info('Add this to your ~/.zshrc if not already present:');
      console.log(chalk.gray('  fpath=(~/.zsh/completions $fpath)'));
      console.log(chalk.gray('  autoload -Uz compinit && compinit'));
    }
  } else if (options.output) {
    writeFileSync(options.output, script);
    success(`Generated ${shell} completion to ${options.output}`);
  } else {
    // Output to stdout
    console.log(script);
  }
}

/**
 * Show setup instructions
 */
function showSetupInstructions() {
  console.log(chalk.cyan('\nALFIE CLI Shell Completion Setup'));
  console.log(chalk.gray('=' .repeat(40)));
  
  console.log(chalk.bold('\n📌 Bash'));
  console.log(chalk.gray('─'.repeat(30)));
  console.log(`
# Option 1: Install automatically
${chalk.green('alfie completion bash --install')}

# Option 2: Manual installation
${chalk.green('alfie completion bash > ~/.local/share/bash-completion/completions/alfie')}

# Then reload your shell
${chalk.green('source ~/.bashrc')}
`);
  
  console.log(chalk.bold('\n📌 Zsh'));
  console.log(chalk.gray('─'.repeat(30)));
  console.log(`
# Option 1: Install automatically
${chalk.green('alfie completion zsh --install')}

# Option 2: Manual installation
${chalk.green('mkdir -p ~/.zsh/completions')}
${chalk.green('alfie completion zsh > ~/.zsh/completions/_alfie')}

# Add to ~/.zshrc (if not already present):
${chalk.gray('fpath=(~/.zsh/completions $fpath)')}
${chalk.gray('autoload -Uz compinit && compinit')}

# Then reload
${chalk.green('source ~/.zshrc')}
`);
  
  console.log(chalk.bold('\n📌 Testing'));
  console.log(chalk.gray('─'.repeat(30)));
  console.log(`
# Type and press Tab:
${chalk.green('alfie <TAB>')}
${chalk.green('alfie chat --<TAB>')}
${chalk.green('alfie session <TAB>')}
`);
}
